### ISSUE TITLE
Can I execute the agents in another server (not in go-server)?

### ISSUE THREAD

**Issue by edtroleis** [gocd-contrib/docker-swarm-elastic-agents#103]
Hello!

I would like to know if it is possible go-server call another server where will be create the containers to execute the pipelines.

go-server -> server with elastic agents

If possible, how do I configure?

Thanks.
Regards.

**Comment by arvindsv** [comment]
@edtroleis Do you mean a separate Docker host? You can provide a Docker Swarm URI in the settings and have it create containers on a remote Docker Swarm.

**Comment by arvindsv** [comment]
Closing this as it's a question and not an issue. We can continue this conversation here, for now, though. :)
