### ISSUE TITLE
Usage of `unix:///var/run/docker.sock` possible

### ISSUE THREAD

**Issue by ChristianKniep** [gocd-contrib/docker-swarm-elastic-agents#11]
I want to beef-up my GoCD stack and run the GoCD server in a SWARM cluster on my Macbook. Thus, I use `unix:///var/run/docker.sock`.

Mounting the socket into the server and using `unix:///var/run/docker.sock` as DOCKER_HOST in the plugin configuration leads to:
"""
**We're sorry, but something went wrong.**
If you are the application owner check the logs for more information.
"""
Is it possible to use a unix-socket in general?

**Comment by ketan** [comment]
By `DOCKER_HOST` do you mean the docker uri parameter in the plugin settings?

![screen shot 2017-03-30 at 5 27 42 pm](https://cloud.githubusercontent.com/assets/10598/24503074/33ec0cbc-156e-11e7-9118-278f40228f25.png)

The above screenshot is the swarm config on `build.gocd.io`, but locally we run using `unix:///var/run/docker.sock`.

Does the server or the plugin logs contain anything in it worth looking at?

**Comment by bdpiparva** [comment]
@ChristianKniep closing the issue. Any reply with asked information will reopen this.
