### ISSUE TITLE
Add ability to read configuration from external file

### ISSUE THREAD

**Issue by viniciusgama** [gocd-contrib/docker-swarm-elastic-agents#12]
The idea is to have a external file, something like a `swarm-elastic-agents.conf` that would go along with the GoCD configuration and the plugin could merge the configuration made through the UI and what is in the file.

The idea came from the implementation made by the slack notifier plugin (https://github.com/ashwanthkumar/gocd-slack-build-notifier), not sure if there are other ways of doing that.

**Comment by ketan** [comment]
Could you explain the motivation behind the config file instead of doing it via the UI?

**Comment by viniciusgama** [comment]
Ease of automation. Currently we have all our GoCD stack creation automated using cloudformation + ansible. Having a way to automate the plugins (not just this one) is the only thing that is not contemplated in our infra code.

Let me know if you need any more details.

**Comment by ketan** [comment]
Closing this issue. Please subscribe to https://github.com/gocd/gocd/issues/3354 to know when this will be implemented. We think we may need to do this in a few releases down the line (no promises :crossed_fingers:).

**Comment by bdpiparva** [comment]
@viniciusgama  --- Closing this issue. Please refer https://api.gocd.org/current/#plugin-settings to create/update plugin settings using api
