### ISSUE TITLE
Upgrade version of spotify docker client to V 8.3.1

### ISSUE THREAD

**Issue by emmeblm** [gocd-contrib/docker-swarm-elastic-agents#15]
Spotify docker client library is now in version 8.3.1 which supports the usage of secrets in swarm. This is important when you need to pull materials from private repos where you need an ssh private key in elastic agents for example.

**Comment by bdpiparva** [comment]
@emmeblm  --- docker client library is updated to version 8.9.0

Checkout PR #30 for more information.
