### ISSUE TITLE
Layout breaks on smaller screens

### ISSUE THREAD

**Issue by ketan** [gocd-contrib/docker-swarm-elastic-agents#40]
On my 15 inch mac. The layout seems to break. If I squeeze the width further, it wraps completely.

<img width="1429" alt="screen shot 2017-09-21 at 8 15 02 am" src="https://user-images.githubusercontent.com/10598/30676690-fe6597f0-9ea4-11e7-8ba7-0f6b650ac16c.png">

**Comment by bdpiparva** [comment]
Closing this as it is resolved in PR #41 

![screen shot 2017-09-28 at 12 58 04 pm](https://user-images.githubusercontent.com/7871209/30954157-c5fe7f64-a44c-11e7-9fcf-c387cb786aa1.png)
