### ISSUE TITLE
Option to map volumes

### ISSUE THREAD

**Issue by remy-tiitre** [gocd-contrib/docker-swarm-elastic-agents#42]
I need to map /var/run/docker.sock into agent container. Your agents probably do not execute docker commands?

**Comment by ketan** [comment]
This is currently not on our radar to implement. Would you be willing to submit a PR?

Usually a adding a new configuration is fairly straight forward. This commit (https://github.com/gocd-contrib/docker-swarm-elastic-agents/commit/50123bb3dac83d0489a314f7ae7a66918ee63610) which implements `--add-host` feature might help

**Comment by remy-tiitre** [comment]
I can look into it. Right now a little busy with GoCD implementation and probably don't use swarm elastic agent for now then. But unless there is an option to map volumes you can't use this plugin for docker image build flows. Will come back to it, when I have more time.

**Comment by remy-tiitre** [comment]
What is your usual release schedule? Right now I have my fork jar added to my gocd agent image, would like to switch back to downloading the release from github.

**Comment by bdpiparva** [comment]
@remy-tiitre --- I will make a release once PR https://github.com/gocd-contrib/docker-swarm-elastic-agents/pull/44 is green.

**Comment by bdpiparva** [comment]
@remy-tiitre --- New release of docker-swarm-plugin available [here](https://github.com/gocd-contrib/docker-swarm-elastic-agents/releases/tag/v2.1.0).
